window:
  width: 1200
  height: 900
panel:
  width: 700
  height: 700
  x: 100
  y: 50
chart:
  height: 100
grid:
  cell_size: 25
mating:
  min_age_percent: 0.10
  min_energy_level: 0.50
  max_range: 10
  mutation_chance: 0.08
  mutation_multiply_border: 0.25 
  mutation_addding_border: 0.05
